networks:
  net_minipress:
    driver: bridge

services:
  core:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    ports:
      - "13887:80"
    volumes :
      - ./MiniPress.core/:/var/php
    working_dir: /var/php
    networks:
      - net_minipress
    depends_on:
      sql:
        condition: service_healthy
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public /var/php/public/Router.php"
  web:
    image: node:lts-alpine
    ports:
      - "13889:3000"
    volumes:
      - ./MiniPress.web:/app
    working_dir: /app
    networks:
      - net_minipress
    command: sh -c "npm install && npm run build && npx serve -l 3000 ."


#############################
# mariadb + adminer
#############################
  sql:
    image: mariadb:latest
    env_file:
      - ./MiniPress.core/conf/.database_env
    volumes:
      - minipress_voldb:/var/lib/mysql
    networks:
      net_minipress:
        aliases:
          - db_minipress
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer
    ports:
      - "13888:8080"
    networks:
      - net_minipress
    command: php -S 0.0.0.0:8080 -t /var/www/html

volumes:
  minipress_voldb: